### ISSUE TITLE
Nutzung der dpv:Purpose Taxonomy

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#11]
**Current behaviour**

Ausgehend von HealthDCAT-AP, sieht das HealthDCAT-AP.de vor, dass Datensets mit der Eigenschaft `dpv:hasPurpose`
beschrieben werden. Der Wertebereich der Property ist nicht weiter eingegrenzt. Im Data Privacy Vocabulary ist der Wertebereich für `dpv:Purpose` allerdings durch eine Taxonomie beschrieben (https://w3c.github.io/dpv/2.0/dpv/#vocab-purposes). Die aktuelle Verwendung, wie sie auch im Beispiel von HealthDCAT-AP illustriert wird, scheint die Property aus dem Datenschutzkontext herauszulösen. 

**Possible enhancement**

Wir empfehlen, dass der Wertebereich von `dpv:Purpose`, als Objekt der Property `dpv:hasPurpose`, wie im DPV vorgesehen, auf die oben genannte Taxonomie beschränkt wird. Dadurch wird sichergestellt, dass die Property im Sinne des Datenschutzes genutzt wird.

**Comment by Markus92** [comment]
During implementation of HealthDCAT-AP in the Dutch national catalogue, we're seeing the same inconsistencies. For now, we are assuming the controlled vocabulary would be used instead of the format used by the HealthDCAT-AP example.

**Comment by JonasPauly-initAG** [comment]
Issue ist zur Umsetzung in Version 0.4 vorgesehen.

**Comment by JonasPauly-initAG** [comment]
Issue ist zur Umsetzung in Version 0.4 vorgesehen.
