### ISSUE TITLE
Informationen über die Nutzung der Daten als neue Eigenschaft aufnehmen

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#13]
**Current behaviour**

Das Datenmodell bietet aktuell keine Möglichkeit, die Nutzung von Datensets nachvollziehen können. 

**Possible enhancement**

Wir schlagen vor,

a) eine Property `healthdcatapde:isCitedIn` aufzunehmen,

b) mit dem Wertebereich URI. die URI (vergleiche landingPage) kann dann auf andere Resourcen verwiesen werden, wie etwa Pressemitteilungen, Apps oder Studien.

c) diesen Change vorzuschlagen für HealthDCAT-AP

**Comment by JonasPauly-initAG** [comment]
Issue ist aufgrund Redundanz mit dct:ReferencedBy geschlossen.
