### ISSUE TITLE
Abweichung vom vorgesehenen Wertebereich für dqv:hasQualityAnnotation

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#15]
**Current behaviour**

Das Datenmodell übernimmt die Property `dqv:hasQualityAnnotation`, ändert allerdings ihren Wertebereich ab. Im dqv ist `dqv:QualityAnnotation` vorgesehen. In HealthDCAT-AP und HealthDCAT-AP.de wird der Wertebereich eingeschränkt auf `dqv:QualityCertificate`, was eine Subklasse von `dpv:QualityAnnotation` ist.

 

**Possible enhancement**

Wir empfehlen, den Wertebereich der Property `dqv:hasQualityAnnotation` aus dem dqv unverändert zu übernehmen.

**Comment by JonasPauly-initAG** [comment]
Issue zur Umsetzung in v0.4 vorgesehen
