### ISSUE TITLE
 Nutzung der Authority Table "Target Audience"

### ISSUE THREAD

**Issue by DavidEdwards-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#17]
**Current behaviour**

HealthDCAT-AP.de beinhaltet aktuell keine Informationen über die verschiedenen Zielgruppen eines Datensatzes.

**Possible enhancement**

Das Vokabular-Team des Publications Office der EU pflegt verschiedene mehrsprachige sogenannte "Authority Tables".
Eine Tabelle ist "Target Audience“, die Informationen über verschiedene potenzielle Zielgruppen eines Datensatzes enthält, wie zum Beispiel Forschende, Medienvertreter oder Bürger.

Wir empfehlen,
a)	eine Property aufzunehmen, zunächst im deutschen Profil mit dem Namen healthdcatapde:targetAudience,
b)	für diese Property Werte als skos:concept mit der URI in Wertebereich des Authority Tables zu verweisen,
c)	ggf. weitere für Zielgruppen von Datenräumen typische Werte einzubringen  (PO Authority Tables),
d)	in einem Konventionenhandbuch eine Unterauswahl der vorgesehenen Werte zu treffen
e)	im EU-Profil diese Eigenschaft vorzuschlagen (DCAT-AP)

[Link zur Authority Table](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/target-audience)

**Comment by JonasPauly-initAG** [comment]
Issue zur Umsetzung in Version 0.4 vorgesehen.
