### ISSUE TITLE
Modell beinhaltete Properties, die in DCAT-AP.de 3.0 entfernt oder als veraltete gekennzeichnet wurden.

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#4]
**Current behaviour**

HealthDCAT-AP.de übernimmt eine Reihe von Eigenschaften von dcat-ap.de, die in DCAT-AP.de 3.0 als veraltet gekennzeichnet sind. Dies betrifft:

`dcatde:qualityProcessURI`
`dcatde:originator`
`dcatde:maintainer`
`owl:versionInfo.`

Darüber hinaus wurden zwei Eigenschaften im Rahmen der Version 3.0 aus DCAT-AP.de entfernt:

`schema:startDate` und
`schema:endDate`.

**Possible enhancement**

HealthDCAT-AP.de schlägt vor

`dcatde:qualityProcessURI` zu streichen,
`dcatde:originator` durch `geodcatap:originator` zu ersetzen,
`dcatde:maintainer `durch `geodcatap:custodian` zu ersetzen
`owl:versionInfo` durch `dcat:version` zu ersetzen
Verzicht auf `schema:startDate` und `schema:endDate`

**Comment by JonasPauly-initAG** [comment]
Issue zur Umsetzung in Version 0.4 vorgesehen.
