### ISSUE TITLE
Fehlerhafter Namensraum der Property hasPersonalData

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#5]
**Current Behaviour**

Das Modell sieht für die Klasse `dcat:Dataset` das Attribut `hasPersonalData` verpflichtend vor. Als Namensraum dieser Property wird HealthDCAT-AP genannt. Allerdings wird diese Eigenschaft von HealthDCAT-AP unverändert aus dpv nachgenutzt. Dafür spricht auch, dass die angegeben RDF Examples von HealthDCAT-AP die Property mit dem Präfix dpv nutzen. 

 

**Possible Enhancement**

Wir empfehlen, den Namensraum, bzw. das Präfix der Property von `hasPersonalData` von healthdcatap zu dpv zu ändern.

**Comment by JonasPauly-initAG** [comment]
Issue ist zur Umsetzung in Version 0.4 vorgesehen.
