### ISSUE TITLE
Unklare Anforderungen an Altersangaben für dcat:Dataset

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#6]
**Current behaviour**

Die Eigenschaften `healthdcatap:maxTypicalAge` und `healthdcatap:minTypicalAge` sind derzeit obligatorisch. Dies könnte bei Datensätzen, die Informationen über andere Entitäten als Menschen enthalten, z. B. Blutzellen, zu Problemen führen. Darüber hinaus hat das übergeordnete Modell HealthDCAT-AP die Kardinalität beider Eigenschaften von obligatorisch auf empfohlen geändert.

Korreliert mit diesem HealthDCAT-AP Issue 10: https://github.com/healthDCAT-AP/Controlled-vocabularies/issues/10

 

**Possible enhancement**

Wir empfehlen, dass die Kardinalität der beiden Eigenschaften von obligatorisch auf empfohlen geändert wird. Zusätzlich sollten die Angaben zur Verwendung der Eigenschaft konkretisiert werden.

**Comment by JonasPauly-initAG** [comment]
Issue ist zur Umsetzung in Version 0.4 vorgesehen.
