### ISSUE TITLE
Antizipierte Nichtverfügbarkeit einer Angabe für dqv:hasQualityAnnotation

### ISSUE THREAD

**Issue by RobinMueller-initAG** [HealthDCAT-AP-de/healthdcat-ap.de#9]
**Current Behaviour**

Das Datenmodell führt `dqv:hasQualityAnnotation` als eine obligatorische Eigenschaft der Domain `dcat:Dataset`. Nach den Erfahrungen von dcat-ap.de, das die analoge Eigenschaft `dcatapde:qualityProcessURI` veraltet und schließlich fallen gelassen hat, ist diese Information bei den Datenbereitstellern selten verfügbar.

 

**Possible Enhancement**

Wir schlagen vor, die Kardinalität von `dqv:hasQualityAnnotation` herabzustufen und sie zu einer empfohlenen statt zu einer obligatorischen Eigenschaft zu machen.

**Comment by JonasPauly-initAG** [comment]
Issue ist zur Umetzung in Version 0.4 vorgesehen.
